// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    $('.grid_item').click(function() {
      return $('#display').css('background-image', $(this).css('background-image'));
    });
    return $('.grid_item:first-child').click();
  });

}).call(this);
