// Generated by CoffeeScript 1.3.3
(function() {
  var loadPhotos;

  loadPhotos = function() {
    return $.get('/tyyc13/photo/json', function(res) {
      var photo, _i, _len;
      for (_i = 0, _len = res.length; _i < _len; _i++) {
        photo = res[_i];
        $('#grid').append("<div class='grid_item' style='background-image: url(" + photo + ");')>");
      }
      $('.grid_item').click(function() {
        return $('#display').css('background-image', $(this).css('background-image'));
      });
      return $('.grid_item:first-child').click();
    });
  };

  $(function() {
    return loadPhotos();
  });

}).call(this);
